# TOMCAT
server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - "*"
            allowed-headers:
              - "*"
#      x-forwarded-for:
#        enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/users/**,/api/auth/**
      - id: question-service
        uri: lb://question-service
        predicates:
        - Path=/api/answers/**,/api/comments/**,/api/questions/**,/api/rates/**
#        filters:
#        - PreserveHostHeader
# EUREKA DISCOVERY
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 5