# TOMCAT
server:
  port: 9090

spring:
  cloud:
    gateway:
#      x-forwarded-for:
#        enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id:question-service
        uri: lb://question-service
        predicates:
        - Path=/question/**
#        filters:
#        - PreserveHostHeader
# EUREKA DISCOVERY
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 5